version: '3'

services:

  sketchfab-service:
    build: .
    container_name: sketchfab-service
    networks:
      - gateway_internal
    environment: 
      FLASK_ENV: development
      FLASK_APP: sketchfab-service
    command: pipenv run flask run --host=0.0.0.0
    labels:
      - "traefik.enable=false" 

networks:
    gateway_internal:
        external: false