debug = false

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "<CHANGE ME!>"
      keyFile = "<CHANGE ME!>"
      # add this cert location to the docker-compose file, under reverse-proxy: volumes. 

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "<CHANGE ME!>"
watch = true
exposedbydefault = false