# Use root/example as user/password credentials
version: '2.0'

services:

  mongo:
    image: mongo
    restart: always
    # ports:
    #   - 27017:27017
    networks:
      - mongo_internal
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - mongo_internal
      - proxy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    labels:
      - "traefik.frontend.rule=Host:mongo-express.docker.localhost"
      - "traefik.backend=mongo-express"
      - "traefik.port=8081"
      - "traefik.docker.network=proxy"

  mongo-service:
    build: .
    container_name: mongo-service
    # ports: 
    #   - "5000:5000"
    depends_on:
      - mongo
    links: 
      - mongo
    networks:
      - mongo_internal
      - proxy
    environment: 
      FLASK_ENV: development
      FLASK_APP: mongo-service
    command: pipenv run flask run --host=0.0.0.0
    labels:
        - "traefik.frontend.rule=Host:mongo.docker.localhost"
        - "traefik.backend=mongo-service"
        - "traefik.port=5000"
        - "traefik.docker.network=proxy"

networks:
    proxy:
        external: true
    mongo_internal:
        external: false