version: '3'

services:
  postgres:
      image: postgres:10
      ports:
          - "5432:5432"
      networks:
          - internal    
      volumes:
          - pg_data:/var/lib/postgresql
      labels:
        - "traefik.enable=false"    

  gateway:
      build: .
    #   ports:
    #       - "8888:8080"
      links:
          - postgres
      depends_on: 
          - postgres
      networks:
        - internal
        - proxy
      command: bash -c "pipenv run python init_db.py && pipenv run python gateway.py"
      labels:
        - "traefik.frontend.rule=Host:gateway.localhost"
        - "traefik.backend=gateway"
        - "traefik.port=8080"
volumes: 
    pg_data:

networks:
    proxy:
        external: true
    internal:
        external: false