version: '3'

services:
  postgres:
      image: postgres:10
      ports:
          - "5432:5432"
      networks:
          - frontend    
      volumes:
          - pg_data:/var/lib/postgresql

  gateway:
      build: .
      ports:
          - "0.0.0.0:8888:8080"
      links:
          - postgres
      depends_on: 
          - postgres
      networks:
        - frontend
      command: bash -c "pipenv run python init_db.py && pipenv run python gateway.py"
      labels:
        - "traefik.frontend.rule=Host:gateway.docker.localhost"
volumes: 
    pg_data:

networks:
    frontend: