version: '3'

services:
  postgres:
      image: postgres:10
    #   ports:
    #       - "5432:5432"
      networks:
          - gateway_internal    
      volumes:
          - pg_data:/var/lib/postgresql
      labels:
        - "traefik.enable=false"    

  gateway:
      build: .
      ports:
          - "8080:8080"
      links:
          - postgres
      depends_on: 
          - postgres
      networks:
        - gateway_internal
        - proxy
      # command: bash -c "pipenv run python init_db.py && pipenv run python gateway.py"
      command: bash -c "pipenv run python gateway.py"
      labels:
        - "traefik.frontend.rule=Host:gateway.docker.localhost"
        - "traefik.backend=gateway"
        - "traefik.port=8080"
        - "traefik.docker.network=proxy"
      volumes:
        - ./data:/gateway/data
  
  reverse-proxy:
      image: traefik # The official Traefik docker image
      command: --api --docker # Enables the web UI and tells Traefik to listen to docker
      ports:
        - "80:80"     # The HTTP port
        - "8080:8080" # The Web UI (enabled by --api)
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      networks:
        - proxy

networks: 
  proxy:
    external: true


volumes: 
    pg_data:

networks:
    proxy:
        external: true
    gateway_internal:
        external: false