version: '3'
services:
  deposit-form:
    build: .
    networks:
      - proxy 
    container_name: admin
    command: npm run serve
    labels:
      - "traefik.frontend.rule=Host:admin.docker.localhost"
      - "traefik.backend=admin"
      - "traefik.port=8080"
      - "traefik.docker.network=proxy"

networks:
    proxy:
        external: true
    